// Copyright 2021 Team 254. All Rights Reserved.
// Author: pat@patfairbank.com (Patrick Fairbank)
//
// Defines a "table" wrapper struct and helper methods for persisting data using Bolt.

package model

import (
	"encoding/json"
	"fmt"
	"go.etcd.io/bbolt"
	"reflect"
	"strings"
)

// Encapsulates all persistence operations for a particular data type represented by a struct. R is the record type and
// I is the type of its ID field, which may be an int or a string-based type such as game.TeamId.
type table[R any, I comparable] struct {
	bolt         *bbolt.DB
	recordType   reflect.Type
	name         string
	bucketKey    []byte
	idFieldIndex *int
	manualId     bool
}

// Registers a new table for a struct.
func newTable[R any, I comparable](database *Database) (*table[R, I], error) {
	var recordType R
	recordTypeValue := reflect.ValueOf(recordType)
	if recordTypeValue.Kind() != reflect.Struct {
		return nil, fmt.Errorf("record type must be a struct; got %v", recordTypeValue.Kind())
	}

	var table table[R, I]
	table.bolt = database.bolt
	table.recordType = reflect.TypeOf(recordType)
	table.name = table.recordType.Name()
	table.bucketKey = []byte(table.name)

	var idZeroValue I
	idType := reflect.TypeOf(idZeroValue)

	// Determine which field in the struct is tagged as the ID and cache its index.
	idFound := false
	for i := 0; i < recordTypeValue.Type().NumField(); i++ {
		field := recordTypeValue.Type().Field(i)
		tags := map[string]struct{}{}
		for _, tag := range strings.Split(field.Tag.Get("db"), ",") {
			tags[tag] = struct{}{}
		}
		if _, ok := tags["id"]; ok {
			if field.Type != idType {
				return nil,
					fmt.Errorf(
						"field in struct %s tagged with 'id' must be of type %v; got %v", table.name, idType, field.Type,
					)
			}
			table.idFieldIndex = new(int)
			*table.idFieldIndex = i
			idFound = true
			_, table.manualId = tags["manual"]
			break
		}
	}
	if !idFound {
		return nil, fmt.Errorf("struct %s has no field tagged as the id", table.name)
	}
	if !table.manualId && idType.Kind() != reflect.Int {
		return nil, fmt.Errorf("struct %s must use manual IDs since its ID is a %v, not an int", table.name, idType)
	}

	// Create the Bolt bucket corresponding to the struct.
	err := table.bolt.Update(
		func(tx *bbolt.Tx) error {
			_, err := tx.CreateBucketIfNotExists(table.bucketKey)
			return err
		},
	)
	if err != nil {
		return nil, err
	}

	return &table, nil
}

// Returns the record with the given ID, or nil if it doesn't exist.
func (table *table[R, I]) getById(id I) (*R, error) {
	record := new(R)
	err := table.bolt.View(
		func(tx *bbolt.Tx) error {
			bucket, err := table.getBucket(tx)
			if err != nil {
				return err
			}

			if recordJson := bucket.Get(idToKey(id)); recordJson != nil {
				return json.Unmarshal(recordJson, record)
			}

			// If the record does not exist, set the record pointer to nil.
			record = nil
			return nil
		},
	)
	return record, err
}

// Returns a slice containing every record in the table, ordered by string representation of ID.
func (table *table[R, I]) getAll() ([]R, error) {
	records := []R{}
	err := table.bolt.View(
		func(tx *bbolt.Tx) error {
			bucket, err := table.getBucket(tx)
			if err != nil {
				return err
			}

			return bucket.ForEach(
				func(key, value []byte) error {
					var record R
					err := json.Unmarshal(value, &record)
					if err != nil {
						return err
					}
					records = append(records, record)
					return nil
				},
			)
		},
	)
	return records, err
}

// Persists the given record as a new row in the table.
func (table *table[R, I]) create(record *R) error {
	// Validate that the record has its ID set to zero or not as expected, depending on whether it is configured for
	// autogenerated IDs.
	value := reflect.ValueOf(record).Elem()
	var zeroId I
	id := value.Field(*table.idFieldIndex).Interface().(I)
	if table.manualId && id == zeroId {
		return fmt.Errorf("can't create %s with zero ID since table is configured for manual IDs", table.name)
	} else if !table.manualId && id != zeroId {
		return fmt.Errorf(
			"can't create %s with non-zero ID since table is configured for autogenerated IDs: %v", table.name, id,
		)
	}

	return table.bolt.Update(
		func(tx *bbolt.Tx) error {
			bucket, err := table.getBucket(tx)
			if err != nil {
				return err
			}

			if !table.manualId {
				// Generate a new ID for the record. Autogenerated IDs are always ints, as enforced by newTable.
				newSequence, err := bucket.NextSequence()
				if err != nil {
					return err
				}
				value.Field(*table.idFieldIndex).SetInt(int64(newSequence))
				id = value.Field(*table.idFieldIndex).Interface().(I)
			}

			// Ensure that a record having the same ID does not already exist in the table.
			key := idToKey(id)
			oldRecord := bucket.Get(key)
			if oldRecord != nil {
				return fmt.Errorf("%s with ID %v already exists: %s", table.name, id, string(oldRecord))
			}

			recordJson, err := json.Marshal(record)
			if err != nil {
				return err
			}
			return bucket.Put(key, recordJson)
		},
	)
}

// Persists the given record as an update to the existing row in the table. Returns an error if the record does not
// already exist.
func (table *table[R, I]) update(record *R) error {
	// Validate that the record has a non-zero ID.
	value := reflect.ValueOf(record).Elem()
	var zeroId I
	id := value.Field(*table.idFieldIndex).Interface().(I)
	if id == zeroId {
		return fmt.Errorf("can't update %s with zero ID", table.name)
	}

	return table.bolt.Update(
		func(tx *bbolt.Tx) error {
			bucket, err := table.getBucket(tx)
			if err != nil {
				return err
			}

			// Ensure that a record having the same ID exists in the table.
			key := idToKey(id)
			oldRecord := bucket.Get(key)
			if oldRecord == nil {
				return fmt.Errorf("can't update non-existent %s with ID %v", table.name, id)
			}

			recordJson, err := json.Marshal(record)
			if err != nil {
				return err
			}
			return bucket.Put(key, recordJson)
		},
	)
}

// Deletes the record having the given ID from the table. Returns an error if the record does not exist.
func (table *table[R, I]) delete(id I) error {
	return table.bolt.Update(
		func(tx *bbolt.Tx) error {
			bucket, err := table.getBucket(tx)
			if err != nil {
				return err
			}

			// Ensure that a record having the same ID exists in the table.
			key := idToKey(id)
			oldRecord := bucket.Get(key)
			if oldRecord == nil {
				return fmt.Errorf("can't delete non-existent %s with ID %v", table.name, id)
			}

			return bucket.Delete(key)
		},
	)
}

// Deletes all records from the table.
func (table *table[R, I]) truncate() error {
	return table.bolt.Update(
		func(tx *bbolt.Tx) error {
			_, err := table.getBucket(tx)
			if err != nil {
				return err
			}

			// Carry out the truncation by way of deleting the whole bucket and then recreate it.
			err = tx.DeleteBucket(table.bucketKey)
			if err != nil {
				return err
			}
			_, err = tx.CreateBucket(table.bucketKey)
			return err
		},
	)
}

// Obtains the Bolt bucket belonging to the table.
func (table *table[R, I]) getBucket(tx *bbolt.Tx) (*bbolt.Bucket, error) {
	bucket := tx.Bucket(table.bucketKey)
	if bucket == nil {
		return nil, fmt.Errorf("unknown table %s", table.name)
	}
	return bucket, nil
}

// Serializes the given ID to a byte array containing its string representation.
func idToKey[I comparable](id I) []byte {
	return []byte(fmt.Sprintf("%v", id))
}
